{
 "title": "Fluent Bit",
 "description": "Inspired by https://raw.githubusercontent.com/fluent/fluent-bit-docs/master/monitoring/dashboard.json",
 "tags": [
  "fluentbit",
  "vm-k8s-stack",
  "vm-k8s-stack",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "query_result(count(global_cluster_info{cluster_name=\"$cluster_name\"}) by (cluster))"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "query_result(count(global_cluster_info) by (cluster_name))"
    }
   },
   {
    "name": "input_plugin_name",
    "label": "input plugin",
    "query": {
     "query": "label_values(fluentbit_input_bytes_total,name)"
    }
   },
   {
    "name": "filter_plugin_name",
    "label": "filter plugin",
    "query": {
     "query": "label_values(fluentbit_filter_add_records_total,name)"
    }
   },
   {
    "name": "output_plugin_name",
    "label": "output plugin",
    "query": {
     "query": "label_values(fluentbit_output_proc_bytes_total,name)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workload CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(workload_cpu_utilization{workload=~\".*fluent-bit.*\",cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(workload_memory_utilization{workload=~\".*fluent-bit.*\",cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(pod_cpu_usage{pod=~\".*fluent-bit.*\",cluster=~\"$cluster\"}) by (cluster,pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pod_memory_usage{pod=~\".*fluent-bit.*\",cluster=~\"$cluster\"}) by (cluster,pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Input Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Input Records Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{cluster=~\"$cluster\",name=~\"$input_plugin_name\"}[5m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{cluster=~\"$cluster\",name=~\"$input_plugin_name\"}[5m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filter Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Filter Drop Records Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rd/s" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_drop_records_total{cluster=~\"$cluster\",name=~\"$filter_plugin_name\"}[5m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filter Add Records Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rd/s" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_add_records_total{cluster=~\"$cluster\",name=~\"$filter_plugin_name\"}[5m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Output Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Output Record Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{cluster=~\"$cluster\",name=~\"$output_plugin_name\"}[5m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{cluster=~\"$cluster\",name=~\"$output_plugin_name\"}[5m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Retry",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{cluster=~\"$cluster\",name=~\"$output_plugin_name\"}[1m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Retry Failed Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rd/s" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{cluster=~\"$cluster\",name=~\"$output_plugin_name\"}[1m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{cluster=~\"$cluster\",name=~\"$output_plugin_name\"}[1m])) by (cluster,pod, name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}