{
 "title": "NVIDIA GPU Pod",
 "tags": [
  "vm-k8s-stack",
  "vm-k8s-stack",
  "vm-k8s-stack",
  "vm-k8s-stack",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "cluster",
    "query": {
     "query": "query_result(global_cluster_info{gpu=\"true\"})"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "query_result({__name__=~\"DCGM_FI_DEV_COUNT|vGPUPodsDeviceAllocated\",cluster=\"$cluster\"})"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "query_result({__name__=~\"DCGM_FI_DEV_COUNT|vGPUPodsDeviceAllocated\", cluster=\"$cluster\", exported_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "gpu",
    "label": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_COUNT{cluster=\"$cluster\", exported_pod=\"$pod\"}, UUID)"
    }
   },
   {
    "name": "gpu_i_id",
    "label": "gpu_profile",
    "query": {
     "query": "label_values(DCGM_FI_DEV_COUNT{cluster=\"$cluster\", UUID=\"$gpu\",exported_pod=\"$pod\"}, GPU_I_ID)"
    }
   },
   {
    "name": "vgpu",
    "query": {
     "query": "label_values(vGPUPodsDeviceAllocated{cluster=\"$cluster\", podname=\"$pod\"}, deviceuuid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "应用概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod GPU Utilization",
   "type": "timeseries",
   "description": "当前 Pod 所使用到的 GPU 卡的比率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kpanda_gpu_pod_utilization{cluster=\"$cluster\",exported_namespace=\"$namespace\",exported_pod=\"$pod\"}",
     "legendFormat": "{{deviceuuid}} {{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "Pod Memory Used",
   "type": "timeseries",
   "description": "当前 Pod 所使用到的 GPU 卡的显存量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "kpanda_gpu_mem_pod_usage{cluster=\"$cluster\",exported_namespace=\"$namespace\",exported_pod=\"$pod\"}",
     "legendFormat": " {{deviceuuid}} {{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "Pod GPU Memory Utilization",
   "type": "timeseries",
   "description": "当前 Pod 所使用到的 GPU 卡的显存比率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kpanda_gpu_mem_pod_utilization{cluster=\"$cluster\",exported_namespace=\"$namespace\",exported_pod=\"$pod\"}",
     "legendFormat": "{{deviceuuid}} {{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  { "title": "GPU 卡- 算力&显存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPU Utilization Details",
   "type": "graph",
   "description": "24 小时内，Pod 关联的 GPU 卡的使用率细节（包含 max、avg、current）",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  avg(\n  max_over_time(\n    DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\" ,GPU_I_ID=~\"${gpu_i_id}\"}\n    )\n  ) by (gpu,UUID)\n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\"} == 0)[29s])\n)\nor \n(\n  avg(\n    max_over_time(\n      DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\" ,GPU_I_ID=~\"${gpu_i_id}\"} * 100\n    )\n  ) by(gpu,GPU_I_PROFILE,GPU_I_ID,UUID)\n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\"} == 1)[29s])\n)\n\n",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": " GPU Memory Used Details ",
   "type": "graph",
   "description": "24 小时内，Pod 关联的 GPU 卡的显存使用量细节\n（包含min\n、max、avg、current）",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Memory Copy Utilization",
   "type": "timeseries",
   "description": "Pod 关联的GPU 卡的显存复制使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  { "title": "GPU 卡-引擎", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GPU Graphics Engine Active",
   "type": "timeseries",
   "description": "表示在一个监控周期内，Graphics或Compute引擎处于Active的时间占总的时间的比例。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 100",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU DRAM Active",
   "type": "timeseries",
   "description": "表示内存带宽利用率（Memory BW Utilization）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_DRAM_ACTIVE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 100",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Tensor Core Engine Active",
   "type": "timeseries",
   "description": "表示在一个监控周期内，Tensor Core管道（Pipe）处于Active时间占总时间的比例。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 100",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU FP16 Engine Active",
   "type": "timeseries",
   "description": "表示在一个监控周期内，FP16管道处于Active的时间占总的时间的比例。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP16_ACTIVE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 100",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU FP32  Engine Active",
   "type": "timeseries",
   "description": "表示在一个监控周期内，FP32 管道处于Active的时间占总的时间的比例。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP32_ACTIVE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 100",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU FP64 Engine Active",
   "type": "timeseries",
   "description": "表示在一个监控周期内，FP64管道处于Active的时间占总的时间的比例。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP64_ACTIVE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 100",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Decode Utilization",
   "type": "timeseries",
   "description": "GPU 卡解码引擎比率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_DEC_UTIL{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Encode Utilization",
   "type": "timeseries",
   "description": "GPU 卡编码引擎比率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_ENC_UTIL{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  { "title": "GPU 卡-温度& 功耗", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "集群下所有 GPU 卡的温度",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU  Power Usage",
   "type": "timeseries",
   "description": "集群下所有 GPU 卡的功率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Total Energy Consumption",
   "type": "timeseries",
   "description": "GPU卡总共消耗的能量",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{cluster=\"$cluster\", UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}) by (gpu)",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "description": "内存频率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 1000  * 1000",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU APP SM Clock",
   "type": "timeseries",
   "description": "应用的SM 时钟频率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_APP_SM_CLOCK{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 1000 * 1000",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU APP Memory Clock",
   "type": "timeseries",
   "description": "应用内存频率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_APP_MEM_CLOCK{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 1000 * 1000",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Video Clock",
   "type": "timeseries",
   "description": "视频引擎频率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_VIDEO_CLOCK{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"} * 1000 * 1000",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU-Clock Throttle Reasons",
   "type": "timeseries",
   "description": "### Clock Throttle Reasons,value mapping:\n* 1 --> GPU_IDLE: Nothing is running on the GPU and the clocks are dropping to Idle state \n* 2 --> CLOCKS_SETTING:  GPU clocks are limited by current setting of applications clocks\n* 4 --> SW_POWER_CAP: SW Power Scaling algorithm is reducing the clocks below requested clocks\n*  8 --> HW_SLOWDOWN: HW Slowdown (reducing the core clocks by a factor of 2 or more) is engaged\n* 10 --> SYNC_BOOST: This GPU has been added to a Sync boost group with nvidia-smi or DCGM in order to maximize performance per watt. \n* 20 --> SW_THERMAL:  SW Thermal Slowdown\n* 80 --> POWER_BRAKE: HW Power Brake Slowdown \n* 100 --> DISPLAY_CLOCKS: GPU clocks are limited by current setting of Display clocks\n\n### Others:\n* These GPUs are assigned to selected pods\n* If multiple pods share a GPU card, the metric value is affected by these pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCK_THROTTLE_REASONS{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  { "title": "其他细节", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "PCIE RX BYTES",
   "type": "timeseries",
   "description": "节点GPU卡通过PCIe总线接收的数据速率。* These GPUs are assigned to selected pods\n* If multiple pods share a GPU card, the metric value is affected by these pods\n* Note that this is from the perspective of the GPU, so copying data from host to device (HtoD)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(DCGM_FI_PROF_PCIE_RX_BYTES{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}[1m])",
     "legendFormat": "GPU{{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "PCIE TX BYTES",
   "type": "timeseries",
   "description": "节点GPU卡通过PCIe总线传输的数据速率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(DCGM_FI_PROF_PCIE_TX_BYTES{cluster=\"$cluster\",UUID=~\"(${gpu}|${vgpu})\",GPU_I_ID=~\"${gpu_i_id}\"}[1m])",
     "legendFormat": "{{UUID}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  }
 ]
}