{
 "title": "Java Monitoring (OpenTelemetry)",
 "tags": [
  "jvm",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage{cluster=\"$cluster\"}, pod)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Java Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "container" },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(process_runtime_jvm_gc_duration_count{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$__interval]))",
     "legendFormat": "GC Count Total",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC Time Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(process_runtime_jvm_gc_duration_sum{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$__interval]))",
     "legendFormat": "GC Time Consumed"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_memory_usage{type=\"heap\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "Usaed"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit{type=\"heap\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "Maximum"
    },
    {
     "expr": "(sum(process_runtime_jvm_memory_limit{type=\"heap\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})) - (sum(process_runtime_jvm_memory_usage{type=\"heap\",cluster=\"$cluster\",  instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Heap Memory Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_memory_usage{type=\"heap\", cluster=\"$cluster\", instance=\"$instance\", pod=\"$pod\", container=\"$container\"}) by (pool, container)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Non-heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_memory_limit{type=\"non_heap\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Maximum"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_usage{type=\"non_heap\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Used"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit{type=\"non_heap\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})- sum(process_runtime_jvm_memory_usage{type=\"non_heap\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) ",
     "legendFormat": "{{container}} Available"
    }
   ]
  },
  {
   "title": "Metaspace Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_memory_usage{cluster=\"$cluster\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Used"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit{cluster=\"$cluster\", cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Maximum"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_threads_count{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) ",
     "legendFormat": "{{container}} Total"
    },
    {
     "expr": "sum(jvm_threads_live{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Active"
    },
    {
     "expr": "sum(jvm_threads_daemon{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Daemon"
    },
    {
     "expr": "sum(jvm_threads_states{instance=\"$instance\", state=\"blocked\", container=\"$container\"})",
     "legendFormat": "{{container}} Blocked"
    }
   ]
  },
  {
   "title": "Classes Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum (process_runtime_jvm_classes_loaded_total{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Loaded",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum (process_runtime_jvm_classes_unloaded_total{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}}  Unloaded"
    },
    {
     "expr": "sum (process_runtime_jvm_classes_current_loaded{cluster=\"$cluster\", instance=\"$instance\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} Current"
    }
   ]
  }
 ]
}