{
 "title": "Metallb",
 "description": "Metallb key metrics",
 "tags": [
  "metallb ",
  "prometheus",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "layer2instance",
    "label": "Layer 2 instance",
    "query": {
     "query": "label_values(metallb_layer2_gratuitous_sent,instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Core" } },
   "targets": [
    {
     "expr": "sum(pod_cpu_usage{pod=~\"metallb-.*\",cluster=~\"$cluster\"}) by (cluster,pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pod_memory_usage{pod=~\".*metallb.*\",cluster=~\"$cluster\"}) by (pod,cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Address in free",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(metallb_allocator_addresses_total{cluster=~\"$cluster\"}) by (pool) - sum(metallb_allocator_addresses_in_use_total{cluster=~\"$cluster\"}) by (pool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stale config",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(metallb_k8s_client_config_stale_bool{cluster=~\"$cluster\"})",
     "legendFormat": "client_config_stale"
    }
   ]
  },
  {
   "title": "Address in used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(metallb_allocator_addresses_in_use_total{cluster=~\"$cluster\"}) by (pool)"
    }
   ]
  },
  {
   "title": "Service annouced",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(metallb_speaker_announced{cluster=~\"$cluster\"}) by (node)"
    }
   ]
  },
  {
   "title": "Layer2 Gratuitous Sending",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metallb_layer2_gratuitous_sent{cluster=~\"$cluster\",instance=~\"$layer2instance\"}[5m])",
     "legendFormat": "gratuitous_sent instance={{instance}} ip={{ip}} "
    }
   ]
  },
  {
   "title": "Client updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metallb_k8s_client_update_errors_total{cluster=~\"$cluster\"}[5m])"
    },
    {
     "expr": "rate(metallb_k8s_client_updates_total{cluster=~\"$cluster\"}[5m])"
    }
   ]
  },
  {
   "title": "Client updates error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metallb_k8s_client_update_errors_total{cluster=~\"$cluster\"}[5m])"
    },
    {
     "expr": "rate(metallb_k8s_client_updates_total{cluster=~\"$cluster\"}[5m])"
    }
   ]
  }
 ]
}