{
 "title": "global cluster opentelemetry collector",
 "tags": [
  "opentelemetry-collector",
  "vm-k8s-stack",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accepted Spans Rate",
   "type": "timeseries",
   "description": "accepted spans from child cluster otel collector",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{service=\"insight-opentelemetry-collector\"}[1m])) by (receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused Spans Rate",
   "type": "timeseries",
   "description": "refused spans Rate from child cluster otel collector",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{service=\"insight-opentelemetry-collector\"}[1m])) by (cluster,receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dropped Spans Rate",
   "type": "timeseries",
   "description": "dropped spans rate by processors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{service=\"insight-opentelemetry-collector\"}[1m])) by (processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Metric Points Rate",
   "type": "timeseries",
   "description": "dropped metric points rate by processors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_metric_points{service=\"insight-opentelemetry-collector\"}[1m])) by (processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Log Records Rate",
   "type": "timeseries",
   "description": "dropped log records rate by processers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{service=\"insight-opentelemetry-collector\"}[1m])) by (processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Traces Beyond Tail Sample Processor Time Threshold",
   "type": "timeseries",
   "description": "droped traces due to beyond sample time threshold",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "increase(otelcol_processor_tail_sampling_sampling_trace_dropped_too_early{service=\"insight-opentelemetry-collector\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sampled traces Rate by Tail Sample Processor",
   "type": "timeseries",
   "description": "Count of traces Rate that were sampled or not.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_count_traces_sampled{service=\"insight-opentelemetry-collector\"}[1m])) by (policy,sampled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sampled Trace Rate By Probabilistic Processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(otelcol_processor_probabilistic_sampler_count_traces_sampled{service=\"insight-opentelemetry-collector\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Sent Spans Rate",
   "type": "timeseries",
   "description": "Sent Spans Rate by exporter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{service=\"insight-opentelemetry-collector\"}[1m])) by (cluster,exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sented Metric Points Rate",
   "type": "timeseries",
   "description": "sented metric points Rate by exporter",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{service=\"insight-opentelemetry-collector\"}[1m])) by (exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sented Log Records Rate",
   "type": "timeseries",
   "description": "sented log records rate by exporter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records{service=\"insight-opentelemetry-collector\",exporter=\"sumologic\"}[1m])) by (exporter)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}