{
 "title": "拨测任务概览",
 "description": "Blackbox Exporter Node",
 "tags": [
  "blackbox",
  "prometheus",
  "vm-k8s-stack",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "query_result(count(global_cluster_info) by (cluster_name))"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(count(global_cluster_info{cluster_name=\"$cluster_name\"}) by (cluster))"
    }
   },
   {
    "name": "job_name",
    "label": "拨测任务",
    "query": {
     "query": "label_values(probe_success{cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "target",
    "label": "探测目标",
    "query": {
     "query": "label_values(probe_success{cluster=\"$cluster\",  job=\"$job_name\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$target Network Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "当前状态响应",
   "type": "stat",
   "description": "Response HTTP status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{cluster=\"$cluster\", job=\"$job_name\", instance=~\"$target\"}",
     "legendFormat": "{{ instane }}"
    }
   ]
  },
  {
   "title": "DNS 响应（延迟）",
   "type": "timeseries",
   "description": "Time taken for website DNS lookup in milli-seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{cluster=\"$cluster\", job=\"$job_name\", instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ping 状态",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\", job=\"$job_name\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 状态码",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\", job=\"$job_name\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 时延",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\", cluster=\"$cluster\", job=\"$job_name\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "IP 协议",
   "type": "stat",
   "description": "Specifies whether probe ip protocol is IP4 or IP6",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ip_protocol{instance=~\"$target\", job=\"$job_name\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 版本",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\", job=\"$job_name\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\", job=\"$job_name\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL 有效期",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\", job=\"$job_name\", cluster=\"$cluster\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}