{
 "title": "Contour - HTTPProxy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(contour_build_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "vhost",
    "query": {
     "query": "label_values({__name__=~\"contour_httpproxy_invalid|contour_httpproxy_valid\", cluster=\"$cluster\"}, vhost)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total HTTProxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(contour_httpproxy{namespace=~\"$namespace\",cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Orphaned HTTProxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(contour_httpproxy_orphaned{namespace=~\"$namespace\",cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Valid HTTProxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(contour_httpproxy_valid{namespace=~\"$namespace\",vhost=~\"$vhost\",cluster=\"$cluster\"}) by (namespace,vhost)",
     "legendFormat": "namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Invalid HTTProxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(contour_httpproxy_invalid{namespace=~\"$namespace\",vhost=~\"$vhost\",cluster=\"$cluster\"}) by (namespace,vhost)",
     "legendFormat": "namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Root HTTProxies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(contour_httpproxy_root{namespace=~\"$namespace\",cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Contour LDS Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_listener_manager_lds_update_failure{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (failure)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_success{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (success)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_rejected{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (rejected)"
    }
   ]
  },
  {
   "title": "Contour CDS Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_cluster_manager_cds_update_success{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_failure{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_rejected{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  },
  {
   "title": "Contour RDS Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_http_rds_update_success{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_http_rds_update_failure{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_http_rds_update_rejected{cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  }
 ]
}