{
 "title": "EgressGateway",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{job=~\"egress.*\"}, job)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconciliation Time Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{job=\"$job\", cluster=\"$cluster\"}[$__range])) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Workers by controller",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum(controller_runtime_max_concurrent_reconciles{job=\"$job\", cluster=\"$cluster\"}) by (controller)"
    }
   ]
  },
  {
   "title": "Concurrent Reconciles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_max_concurrent_reconciles{job=\"$job\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Cert Watcher Read Certificate Total",
   "type": "stat",
   "description": "If fsnotify.Watcher detects a change in the certificate file, this indicator will be increased.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "certwatcher_read_certificate_total{job=\"$job\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reconciliation Time by controller (P90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(90/100, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$job\", cluster=\"$cluster\"}[5m])) by (controller,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller Only", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Node Controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(controller_runtime_reconcile_total{controller=\"node\",job=~\"egress.*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "EgressGateway Controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(controller_runtime_reconcile_total{controller=\"egressGateway\",job=~\"egress.*\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "EgressNode Controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(controller_runtime_reconcile_total{controller=\"egressNode\",job=~\"egress.*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Agent Only", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "iptables restore calls",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "round(increase(iptables_restore_calls{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(increase(iptables_restore_errors{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iptables save calls",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "round(increase(iptables_save_calls{cluster=\"$cluster\"}[$__rate_interval]))"
    },
    {
     "expr": "round(increase(iptables_save_errors{cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "iptables chains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "iptables_chains{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "iptables rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "iptables_rules{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "iptables lines executed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(iptables_lines_executed{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iptables lock acquire secs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "iptables_lock_acquire_secs{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iptables lock retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "iptables_lock_acquire_secs{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}