{
 "title": "Spiderpool",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total ippool counts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spiderpool_total_ippool_counts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total subnet counts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spiderpool_total_subnet_counts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IP allocation counts",
   "type": "timeseries",
   "description": "spiderpool IPAM IP allocation status",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "spiderpool_ipam_allocation_counts_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_allocation_failure_counts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ip allocation durations",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "spiderpool_ipam_allocation_average_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_allocation_max_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_allocation_min_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_allocation_latest_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ip allocation duration distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spiderpool_ipam_allocation_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP release&GC counts",
   "type": "timeseries",
   "description": "spiderpool IP release and IP GC status",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "spiderpool_ipam_release_counts_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_release_failure_counts_total",
     "legendFormat": "__auto"
    },
    { "expr": "spiderpool_ip_gc_counts_total", "legendFormat": "__auto" },
    {
     "expr": "spiderpool_ip_gc_failure_counts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP release durations",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "spiderpool_ipam_release_average_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_release_max_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_release_min_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "spiderpool_ipam_release_latest_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP release duration distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spiderpool_ipam_release_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}