{
 "title": "Ascend NPU Dashboard",
 "description": "ascend monitor",
 "tags": [
  "ascend",
  "昇腾",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(npu_chip_info_name{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "npu_id",
    "label": "NPU_ID",
    "query": {
     "query": "label_values(npu_chip_info_name{cluster=~\"$cluster\",node=~\"$node\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "昇腾AI名称和ID",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "npu_id",
   "targets": [
    {
     "expr": "npu_chip_info_name{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU{{label_name}}"
    }
   ]
  },
  {
   "title": "昇腾AI处理器数目",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_npu_nums{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器的AI Core当前频率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_aicore_current_freq{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器网络健康状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_network_status{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器网口Link状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_link_status{instance=\"$instance\", id=\"$npu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器网口实时接收速率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_bandwidth_rx{cluster=~\"$cluster\", id=~\"$npu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器网口实时发送速率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_bandwidth_tx{cluster=~\"$cluster\", id=~\"$npu_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "昇腾AI处理器健康状态",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "expr": "npu_chip_info_health_status{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}健康状态"
    }
   ]
  },
  {
   "title": "昇腾AI处理器进程占用内存信息",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "repeat": "npu_id",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "npu_chip_info_process_info{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}_进程{{process_id}}"
    }
   ]
  },
  {
   "title": "昇腾AI处理器AI Core利用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "npu_chip_info_utilization{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}利用率"
    }
   ]
  },
  {
   "title": "昇腾AI处理器温度",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "npu_chip_info_temperature{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}AI处理器温度"
    }
   ]
  },
  {
   "title": "昇腾AI处理器功耗",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "npu_chip_info_power{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}AI处理器功耗"
    }
   ]
  },
  {
   "title": "昇腾AI处理器DDR内存",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "npu_chip_info_total_memory{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}总DDR内存"
    },
    {
     "expr": "npu_chip_info_used_memory{instance=\"$instance\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}已用DDR内存"
    },
    {
     "expr": "npu_chip_info_total_memory{instance=\"$instance\", id=\"$npu_id\"}-npu_chip_info_used_memory{instance=\"$instance\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}可用DDR内存"
    },
    {
     "expr": "npu_chip_info_used_memory{instance=\"$instance\", id=\"$npu_id\"}/npu_chip_info_total_memory{instance=\"$instance\", id=\"$npu_id\"}*100",
     "legendFormat": "NPU_{{id}}DDR内存使用率"
    }
   ]
  },
  {
   "title": "昇腾AI处理器HBM内存",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "npu_chip_info_hbm_total_memory{cluster=\"$cluster\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}总HBM内存"
    },
    {
     "expr": "npu_chip_info_hbm_used_memory{instance=\"$instance\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}已用HBM内存"
    },
    {
     "expr": "npu_chip_info_hbm_total_memory{instance=\"$instance\", id=\"$npu_id\"}-npu_chip_info_hbm_used_memory{instance=\"$instance\", id=\"$npu_id\"}",
     "legendFormat": "NPU_{{id}}可用HBM内存"
    },
    {
     "expr": "npu_chip_info_hbm_used_memory{instance=\"$instance\", id=\"$npu_id\"}/npu_chip_info_hbm_total_memory{instance=\"$instance\", id=\"$npu_id\"}*100",
     "legendFormat": "NPU_{{id}}HBM内存使用率"
    }
   ]
  }
 ]
}