{
 "title": "Calico",
 "description": "Calico cluster monitoring dashboard",
 "tags": [ "calico" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "IPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ipam_allocations_in_free",
   "type": "barchart",
   "description": "The numbers of free IPs currently",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(ipam_ippool_size{cluster=~\"$cluster\"}) by (ippool) - sum(ipam_allocations_in_use{cluster=~\"$cluster\"}) by (ippool)"
    }
   ]
  },
  {
   "title": "IPAM allocations in use",
   "type": "barchart",
   "description": "IPs currently allocated in IPAM to a workload or tunnel endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(ipam_allocations_in_use{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "IPAM block ",
   "type": "barchart",
   "description": "IPs currently allocated in IPAM to a workload or tunnel endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(ipam_blocks_per_node{cluster=~\"$cluster\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IPAM allocations borrowed",
   "type": "barchart",
   "description": "IPs currently allocated in IPAM to a workload or tunnel endpoint, where the allocation was borrowed from a block affine to another node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(ipam_allocations_borrowed{cluster=~\"$cluster\"}) by (node)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Calico-node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(pod_cpu_usage{pod=~\"calico-node-.*\",cluster=~\"$cluster\"}) by (cluster,pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Calico-node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Felix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active Local Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_endpoints{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Local Policies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_policies{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Local Selectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_selectors{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Workload Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_workload_endpoints{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Host Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_host_endpoints{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active IP Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_ipsets_calico{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clusters Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_hosts{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IP Set Command Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_ipset_errors", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active IP Tables Chains",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_iptables_chains{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IP Tables Restore Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_iptables_restore_errors{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IP Tables Save Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_iptables_save_errors{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dataplane failed updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_int_dataplane_failures", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Felix Resyncing Datastore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_resyncs_started{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}