{
 "title": "NVIDIA GPU Node",
 "tags": [
  "vm-k8s-stack",
  "vm-k8s-stack",
  "vm-k8s-stack",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "cluster",
    "query": {
     "query": "query_result(global_cluster_info{gpu=\"true\"})"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_COUNT{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_COUNT{cluster=\"$cluster\"},gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "基本信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GPU",
   "type": "stat",
   "description": "The total number of GPUs, including the number of MIG instances.\n\n\n\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kpanda_gpu_count{cluster=\"$cluster\",node=~\"${node}\"}"
    }
   ]
  },
  {
   "title": "GPU Mode",
   "type": "stat",
   "description": "节点上 GPU 卡的模式使用模式，包含 整卡模式、MIG 模式、vGPU 模式",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kpanda_gpu_mode{cluster=\"$cluster\",node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg Utilization ",
   "type": "gauge",
   "description": "节点上所有 GPU 卡的平均使用率",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg(\n  max_over_time(\n    DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"}[29s]\n    )\n  ) \n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 0)[29s])\n)\nor \n(\n  avg(\n    max_over_time(\n      DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"}[29s] * 100\n    )\n  ) \n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 1)[29s])\n)\n"
    }
   ]
  },
  {
   "title": "GPU Avg Memory Utilization",
   "type": "gauge",
   "description": "节点上所有 GPU 卡的平均显存使用率",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(DCGM_FI_DEV_FB_USED{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"}[29s])) / sum(max_over_time(DCGM_FI_DEV_FB_USED{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"} + DCGM_FI_DEV_FB_FREE{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"} [29s])) * 100"
    }
   ]
  },
  {
   "title": "GPU Driver Version",
   "type": "stat",
   "description": "节点上 GPU 卡驱动的版本信息",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\",node=~\"$node\",gpu=~\"$gpu\"}",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Specifications",
   "type": "table",
   "description": "节点上 GPU 卡规格信息",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\",node=~\"$node\",gpu=~\"$gpu\"}",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  { "title": "算力&显存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GPU Utilization Details",
   "type": "graph",
   "description": "24 小时内，节点上所有 GPU 卡的使用率细节（包含 max、avg、current）",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"}\n    )\n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 0))\n)\nor \n(\n    (\n      DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"} * 100\n    )\n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 1))\n)\n",
     "legendFormat": "{{node}} - GPU{{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": " GPU Memory Used Details ",
   "type": "graph",
   "description": "24 小时内，节点上所有 GPU 卡的显存使用量细节\n（包含min\n、max、avg、current）",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node}} -  GPU {{gpu}} {{GPU_I_PROFILE}} {{GPU_I_ID}} "
    }
   ]
  },
  { "title": "GPU卡", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Node  Details",
   "type": "table",
   "description": "Details of all gpu nodes",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(node, UUID, gpu) (max_over_time(DCGM_FI_DEV_FB_USED{cluster=\"$cluster\",node=\"$node\"}[29]))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(max_over_time(DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\",node=\"$node\"})) by (node,UUID,gpu)",
     "legendFormat": "Utilization"
    },
    {
     "expr": "avg(max_over_time(DCGM_FI_DEV_POWER_USAGE{cluster=\"$cluster\",node=\"$node\"})) by (node,UUID,gpu,DCGM_FI_DRIVER_VERSION,modelName)",
     "legendFormat": "Power"
    },
    {
     "expr": "avg(max_over_time(DCGM_FI_DEV_GPU_TEMP{cluster=\"$cluster\",node=\"$node\"})) by (node,UUID,gpu)",
     "legendFormat": "GPU Temperature"
    },
    {
     "expr": "avg(max_over_time(DCGM_FI_DEV_MEMORY_TEMP{cluster=\"$cluster\",node=\"$node\"})) by (node,UUID,gpu)",
     "legendFormat": "Memory Temperature"
    },
    {
     "expr": "avg(max_over_time(DCGM_FI_DEV_MEM_COPY_UTIL{cluster=\"$cluster\",node=\"$node\"})) by (node,UUID,gpu)",
     "legendFormat": "Memory Copy Utilization"
    }
   ]
  }
 ]
}