{
 "title": "NVIDIA GPU Cluster",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "tags": [
  "vm-k8s-stack",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "cluster",
    "query": {
     "query": "query_result(global_cluster_info{gpu=\"true\"})"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_COUNT{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_COUNT{cluster=\"$cluster\"},gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total GPU",
   "type": "stat",
   "description": "集群下所有的 GPU 卡数量，切分的 MIG 实例也将会被统计成的单张的物理卡\n\n\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kpanda_gpu_count{cluster=\"$cluster\",node=~\"${node}\"}"
    }
   ]
  },
  {
   "title": "GPU Avg Utilization",
   "type": "gauge",
   "description": "集群下所有 GPU 卡的平均使用率",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg(\n  max_over_time(\n    DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"}[29s]\n    )\n  ) \n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 0)[29s])\n)\nor \n(\n  avg(\n    max_over_time(\n      DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"}[29s] * 100\n    )\n  ) \n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 1)[29s])\n)\n\n"
    }
   ]
  },
  {
   "title": "GPU Avg Memory Utilization",
   "type": "gauge",
   "description": "集群下所有 GPU 卡的平均显存使用率",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(DCGM_FI_DEV_FB_USED{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"}[29s])) / sum(max_over_time(DCGM_FI_DEV_FB_USED{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"} + DCGM_FI_DEV_FB_FREE{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"} [29s])) * 100"
    }
   ]
  },
  {
   "title": "GPU Driver Version",
   "type": "stat",
   "description": "节点上 GPU 卡驱动的版本信息",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\",node=~\"$node\",gpu=~\"$gpu\"}",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU  Power Usage",
   "type": "timeseries",
   "description": "集群下所有 GPU 卡的功率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node}} - GPU{{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "集群下所有 GPU 卡的温度",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node}} - GPU{{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Utilization Details",
   "type": "graph",
   "description": "24 小时内，集群下所有 GPU 卡的使用率细节（包含 max、avg、current）",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"}\n    )\n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 0))\n)\nor \n(\n    (\n      DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster=\"$cluster\", node=~\"${node}\", gpu=~\"${gpu}\"} * 100\n    )\n  unless \n  absent(max_over_time(DCGM_FI_DEV_MIG_MODE{cluster=\"$cluster\", node=~\"$node\"} == 1))\n)\n",
     "legendFormat": "{{node}} - GPU{{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Memory Used Details",
   "type": "graph",
   "description": "24 小时内，集群下所有 GPU 卡的显存使用量细节\n（包含min\n、max、avg、current）",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node}} -  GPU{{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  },
  {
   "title": "GPU Memory Copy Utilization",
   "type": "timeseries",
   "description": "集群下所有 GPU 卡的显存复制使用率",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{cluster=\"$cluster\",node=~\"${node}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node}} - GPU{{gpu}}  {{GPU_I_PROFILE}}  {{GPU_I_ID}} "
    }
   ]
  }
 ]
}