{
 "title": "HwameiStor Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Storage Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hwameistor_localstoragenode_status{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(hwameistor_localstoragenode_status{status=\"Ready\",cluster=\"$cluster\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(hwameistor_localstoragenode_status{status=\"Maintain\",cluster=\"$cluster\"})",
     "legendFormat": "Maintain"
    },
    {
     "expr": "sum(hwameistor_localstoragenode_status{status=\"Offline\",cluster=\"$cluster\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Total\",cluster=\"$cluster\"}",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Used\",cluster=\"$cluster\"}",
     "legendFormat": "Allocated Capacity"
    }
   ]
  },
  {
   "title": "Storage Usage Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Total\",cluster=\"$cluster\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Used\",cluster=\"$cluster\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Free\",cluster=\"$cluster\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "hwameistor_localstoragenode_volumecount{kind=\"Total\",cluster=\"$cluster\"}",
     "legendFormat": "volTotal"
    },
    {
     "expr": "hwameistor_localstoragenode_volumecount{kind=\"Used\",cluster=\"$cluster\"}",
     "legendFormat": "volUsed"
    },
    {
     "expr": "hwameistor_localstoragenode_volumecount{kind=\"Free\",cluster=\"$cluster\"}",
     "legendFormat": "volFree"
    },
    {
     "expr": "hwameistor_localstoragenode_status{cluster=\"$cluster\"}",
     "legendFormat": "Status"
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Status Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hwameistor_localvolume_status{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(hwameistor_localvolume_status{status=\"Ready\",cluster=\"$cluster\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(hwameistor_localvolume_status{cluster=\"$cluster\"}) - sum(hwameistor_localvolume_status{status=\"Ready\", cluster=\"$cluster\"})",
     "legendFormat": "Not Ready"
    }
   ]
  },
  {
   "title": "Type Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hwameistor_localvolume_status{type=\"HA\",cluster=\"$cluster\"})",
     "legendFormat": "HA"
    },
    {
     "expr": "count(hwameistor_localvolume_status{type=\"NonHA\",cluster=\"$cluster\"})",
     "legendFormat": "non-HA"
    },
    {
     "expr": "count(hwameistor_localvolume_status{type=\"Convertible\",cluster=\"$cluster\"})",
     "legendFormat": "Convertible"
    },
    {
     "expr": "count(hwameistor_localvolume_status{type=\"Disk\",cluster=\"$cluster\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hwameistor_localvolumereplica_status{cluster=\"$cluster\"}",
     "legendFormat": "Auto"
    },
    {
     "expr": "hwameistor_localvolume_capacity{kind=\"Allocated\",cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwameistor_localvolume_capacity{kind=\"Used\",cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Status Overview",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hwameistor_localdisk_capacity{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{status=\"Bound\",cluster=\"$cluster\"})",
     "legendFormat": "Bound"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{status=\"Available\",cluster=\"$cluster\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{status=\"Pending\",cluster=\"$cluster\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{reserved=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "Reseverd"
    }
   ]
  },
  {
   "title": "Health Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hwameistor_localdisk_capacity{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}