{
 "title": "workload cluster opentelemetry collector",
 "tags": [
  "vm-k8s-stack",
  "opentelemetry-collector",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(calls_total{cluster=\"$cluster\"}, k8s_namespace_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accepted spans Rate",
   "type": "timeseries",
   "description": "accept spans rate by receiver",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\"}[1m])) by (cluster,receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused spans Rate",
   "type": "timeseries",
   "description": "spans refuse rate from language agent/SDK.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\"}[1m])) by (cluster,receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted Spans Rate Per Service",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(calls_total{cluster=\"$cluster\",k8s_namespace_name=~\"$namespace\"}[1m])) by (service_name,k8s_namespace_name)",
     "legendFormat": "{{service_name}}/{{k8s_namespace_name}}"
    }
   ]
  },
  { "title": "processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Dropped Spans Rate",
   "type": "timeseries",
   "description": "dropped spans rate by processors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{service=\"insight-agent-opentelemetry-collector\"}[1m])) by (cluster,processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Metric Points Rate",
   "type": "timeseries",
   "description": "dropped metric points rate by processors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_metric_points{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\"}[1m])) by (cluster,processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Sented Spans Rate",
   "type": "timeseries",
   "description": "Sented Spans Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\",exporter=\"otlp/global\"}[1m])) by (cluster,exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sented Spans Failed Rate",
   "type": "timeseries",
   "description": "Sented Spans failed Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{cluster=\"$cluster\",service=\"insight-opentelemetry-collector\"})[1m]) by (cluster,exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current  Retry Queue Size Rate",
   "type": "timeseries",
   "description": "current  retry queue size Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_queue_size{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\"}[1m])) by (cluster,exporter)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}