{
 "title": "insight tracing debug",
 "description": "it uses to debug span data transmission",
 "tags": [
  "vm-k8s-stack",
  "vm-k8s-stack",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(calls_total{cluster=\"$cluster\"}, k8s_namespace_name)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "workload opentelemetry collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Accepted spans Rate From Probe",
   "type": "timeseries",
   "description": "accept spans rate by receiver",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\"}[1m])) by (cluster,receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused spans Rate From Probe",
   "type": "timeseries",
   "description": "spans refuse rate from language agent/SDK.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\"}[1m])) by (cluster,receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sented Spans Rate To Global Collector",
   "type": "timeseries",
   "description": "Sented Spans Rate",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{service=\"insight-agent-opentelemetry-collector\",cluster=\"$cluster\",exporter=\"otlp/global\"}[1m])) by (cluster,exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sented Spans Failed Rate To Global",
   "type": "timeseries",
   "description": "Sented Spans failed Rate",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{cluster=\"$cluster\",service=\"insight-opentelemetry-collector\"})[1m]) by (cluster,exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted Spans Rate Per Service",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(calls_total{cluster=\"$cluster\",k8s_namespace_name=~\"$namespace\"}[1m])) by (service_name,k8s_namespace_name)",
     "legendFormat": "{{service_name}}/{{k8s_namespace_name}}"
    }
   ]
  },
  { "title": "global opentelemetry collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Accepted Spans Rate From Workload Collector",
   "type": "timeseries",
   "description": "accepted spans from child cluster otel collector",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{service=\"insight-opentelemetry-collector\"}[1m])) by (receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refused Spans Rate From Workload Collector",
   "type": "timeseries",
   "description": "refused spans from child cluster otel collector",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{service=\"insight-opentelemetry-collector\"}[1m])) by (cluster,receiver)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Spans Rate To Jaeger",
   "type": "timeseries",
   "description": "Sent Spans Rate by exporter",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{service=\"insight-opentelemetry-collector\",exporter=\"otlp/jaeger\"}[1m])) by (cluster,exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sented Audit Log Records Rate To Ghippo",
   "type": "timeseries",
   "description": "sented log records rate by exporter",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records{service=\"insight-opentelemetry-collector\",exporter=\"sumologic\"}[1m])) by (exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Map Edge Table(Client Side)",
   "type": "table",
   "description": "The select button only effect the client_k8s_cluster_id and client_k8s_namespace_name labels",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(traces_service_graph_request_total{client_k8s_cluster_id=\"$cluster\",client_k8s_namespace_name=~\"$namespace\"}) by (client,server)"
    }
   ]
  },
  {
   "title": "Service Map Edge Table(Server Side)",
   "type": "table",
   "description": "The select button only effect the server_k8s_cluster_id and server_k8s_namespace_name labels",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(traces_service_graph_request_total{server_k8s_cluster_id=\"$cluster\",server_k8s_namespace_name=~\"$namespace\"}) by (client,server)"
    }
   ]
  },
  { "title": "global jaeger collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Jager Received Span Rate",
   "type": "timeseries",
   "description": "Jager Received Span Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_collector_spans_received_total[1m])) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jager Dropped Span Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_collector_spans_dropped_total[1m])) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger Queue Capacity/Current Queue Count",
   "type": "timeseries",
   "description": "Queue capacity Count. If the current queue is equal to queue capacity, jaeger will drop spans.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jaeger_collector_queue_capacity) by (cluster)",
     "legendFormat": "queue capacity"
    },
    {
     "expr": "sum(jaeger_collector_queue_length) by (cluster)",
     "legendFormat": "current queue"
    }
   ]
  },
  {
   "title": "Jaeger In Queue P95 Latency",
   "type": "timeseries",
   "description": "Jaeger In Queue P95 Latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_collector_in_queue_latency_bucket[1m])) by (le,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger bulk Index Insert Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_bulk_index_inserts_total[1m])) by (cluster)",
     "legendFormat": "bulk_index"
    }
   ]
  },
  {
   "title": "Jaeger Bulk Index P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_bulk_index_latency_ok_bucket[1m])) by (le,cluster))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger Bulk Index Error Rate",
   "type": "timeseries",
   "description": "Jaeger bulk Index Error Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_bulk_index_errors_total[1m])) by (cluster)",
     "legendFormat": "bulk_index"
    }
   ]
  },
  {
   "title": "Jaeger Bulk Index Error P95 Latency",
   "type": "timeseries",
   "description": "Jaeger Bulk Index Error P95 Latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_bulk_index_latency_err_bucket[1m])) by (le,cluster))",
     "legendFormat": "bulk_index"
    }
   ]
  }
 ]
}