{
 "title": "Java 监控 (JMX Exporter)",
 "tags": [ "jvm" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__=~\"jvm_info|process_uptime_seconds\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values({__name__=~\"jvm_info|process_uptime_seconds\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"jvm_info|process_uptime_seconds\",  cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values({__name__=~\"jvm_info|process_uptime_seconds\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JMX Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "container" },
  {
   "title": "GC 次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_count{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[5m]))",
     "legendFormat": "总 GC 次数"
    },
    {
     "expr": "rate(jvm_gc_pause_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Time Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[$__interval]))",
     "legendFormat": "GC 耗时"
    },
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[1m])/rate(jvm_gc_pause_seconds_count{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "使用内存"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "内存峰值"
    },
    {
     "expr": "(sum(jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})) - sum(jvm_memory_bytes_used{area=\"heap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "可用内存"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})",
     "legendFormat": "使用内存"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})",
     "legendFormat": "申请内存"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\", area=\"heap\"})",
     "legendFormat": "内存峰值"
    }
   ]
  },
  {
   "title": "堆内存详情",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (pool)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"nonheap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 内存限制"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"nonheap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 内存用量"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"nonheap\",instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})- sum(jvm_memory_bytes_used{area=\"nonheap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) ",
     "legendFormat": "{{container}} 可用内存"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 内存用量"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 内存峰值"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\",instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})- sum(jvm_memory_used_bytes{area=\"nonheap\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) ",
     "legendFormat": "{{container}} 可用内存"
    }
   ]
  },
  {
   "title": "Metaspace Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_max{pool=\"Metaspace\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 元空间内存总量"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pool=\"Metaspace\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 元内存使用量"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{id=\"Metaspace\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 元空间内存总量"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{id=\"Metaspace\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 元内存使用量"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(jvm_threads_state{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}) ",
     "legendFormat": "{{container}} 总线程数"
    },
    {
     "expr": "sum(jvm_threads_current{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 活跃线程数"
    },
    {
     "expr": "sum(jvm_threads_daemon{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 守护线程数"
    },
    {
     "expr": "sum(jvm_threads_states{state=\"blocked\", instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 阻塞线程数"
    },
    {
     "expr": "sum(jvm_threads_deadlocked{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "死锁线程数"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{container}} Live线程"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{container}} 守护线程数"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}",
     "legendFormat": "{{container}} Peak线程"
    }
   ]
  },
  {
   "title": "Classes Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(jvm_classes_loaded_total{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 加载类个数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "sum(jvm_classes_unloaded_total{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 卸载类个数"
    },
    {
     "expr": "sum(jvm_classes_currently_loaded{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 当前类个数"
    },
    {
     "expr": "sum(jvm_classes_loaded_classes{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 加载类个数"
    },
    {
     "expr": "sum(jvm_classes_unloaded_classes_total{instance=\"$instance\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}} 卸载类个数"
    }
   ]
  }
 ]
}